services:
- type: web
  name: pydio-cells
  env: docker
  plan: standard
  disk:
    name: cellsdir
    mountPath: /var/cells
    sizeGB: 20
  envVars:
  - key: CELLS_DB_HOST
    fromService:
      name: mysql-pydio-cells
      type: pserv
      property: host
  - key: CELLS_DB_NAME
    fromService:
      name: mysql-pydio-cells
      type: pserv
      envVarKey: MYSQL_DATABASE
  - key: CELLS_DB_USER
    fromService:
      name: mysql-pydio-cells
      type: pserv
      envVarKey: MYSQL_USER
  - key: CELLS_DB_PASSWORD
    fromService:
      name: mysql-pydio-cells
      type: pserv
      envVarKey: MYSQL_PASSWORD
- type: pserv
  name: mysql-pydio-cells
  repo: https://github.com/render-examples/mysql.git
  env: docker
  plan: standard
  disk:
    name: mysqldir
    mountPath: /var/lib/mysql
    sizeGB: 20
  envVars:
  - key: MYSQL_DATABASE
    value: cells
  - key: MYSQL_USER
    value: pydio
  - key: MYSQL_PASSWORD
    generateValue: true
  - key: MYSQL_ROOT_PASSWORD
    generateValue: true
