services:
- type: web
  name: pydio-cells
  env: docker
  plan: standard
  disk:
    name: cellsdir
    mountPath: /var/cells
    sizeGB: 10
  envVars:
  - key: CELLS_LOG_LEVEL
    value: production
  - key: CELLS_NO_TLS
    value: 1
